services:
  web:
    build:
      context: ./
      target: dev
    image: simulador-freelance:dev
    volumes:
       - .:/build-stage
       - /build-stage/node_modules
    ports:
      - 5173:5173
